# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'CardsModules' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardsModules

  pod 'HydrogenCards', :path => './'
  pod 'Alamofire'
  pod 'iOSDropDown'
  pod 'SwiftJWT'

  post_install do |installer|   
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
          end
        end
      end
  end

end
